.catalog:
  name: Maildev
  version: latest
  uuid: maildev-0
  questions:
    - variable: SMTP_PORT
    description: 'SMTP port'
    label: 'SMTP Port :'
    required: true
    default: 25
    type: int
    - variable: UI_PORT
    description: 'UI port'
    label: 'UI Port:'
    required: true
    default: 80
    type: int
maildev:
  scale: 1
