name: Maildev
description: 'SMTP Server + Web Interface for viewing and testing emails during development.https://github.com/djfarrelly/MailDev http://danfarrelly.nyc/MailDev/'
category: Utils
version: latest
