kimsufi :
  image: cl3m3nt/kimsufi-availability:v0.1
  environment:
    SERVER_WARN: "${srv}"
    ZONE: "${zone}"
    TOKEN: "${token}"
    USERID: "${id}"
    TIMESLEEP: "${sleep}"
    TIMERENOTIFY: "${renotify}"
