.catalog:
  name: "kimsufiChecker"
  version: "v0.1"
  description: "Auto checker for srv ovh kimsufi - https://github.com/cl3m3nt666/kimsufi-availability"
  minimum_rancher_version: v0.46.0
  questions:
    - variable: "srv"
      type: string
      required: true
      label: "reference Kimsufi srv"
      description: "reference Kimsufi srv"
    - variable: "zone"
      type: string
      required: false
      label: "geographical zones ex:rbx"
      description: "geographical zones"
    - variable: "token"
      type: string
      required: true
      label: "Telegram token"
      description: "Telegram token"
    - variable: "id"
      type: string
      required: true
      label: "Telegram id"
      description: "Telegram id"
    - variable: "sleep"
      type: string
      required: true
      label: "Time sleep"
      description: "Time sleep between check availability (in seconde)"
      default: 1
    - variable: "renotify"
      type: string
      required: true
      label: "Time for re-notify user"
      description: "Time for re-notify user (in seconde)"
      default: 100

environment:
  SERVER_WARN: 143sys1
  ZONE: rbx
  TOKEN:
  USERID:
  TIMESLEEP: 1
  TIMERENOTIFY: 60
