registry:
  image: registry:2
  labels:
    io.rancher.scheduler.affinity:host_label: registry=true
  environment:
    REGISTRY_AUTH: htpasswd
    REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
  volumes:
    - /auth:/auth
  ports:
  - 5000:5000/tcp
registry-web:
  image: hyper/docker-registry-web
  environment:
    REGISTRY_URL: "http://registry:5000/v2"
    REGISTRY_NAME: "${hostname}:5000"
    REGISTRY_BASIC_AUTH: "${pass}"
  links:
    - registry
  ports:
  - 8080:8080/tcp
